package com.pranab.bhitte_patro

import android.appwidget.AppWidgetManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity() {
    private val CHANNEL = "group.bhittepatroapp"
    private val PREFS_NAME = "BhittePatroWidgetPrefs"

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            if (call.method == "updateAndroidWidget") {
                val data = call.arguments as? Map<String, Any>
                if (data != null) {
                    saveWidgetData(data)
                    triggerWidgetUpdate()
                    result.success(true)
                } else {
                    result.error("INVALID_ARGUMENT", "Widget data map was null", null)
                }
            } else {
                result.notImplemented()
            }
        }
    }

    private fun saveWidgetData(data: Map<String, Any>) {
        val sharedPref = getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        with(sharedPref.edit()) {
            // Store reference anchor data
            putInt("syncAdYear", (data["syncAdYear"] as? Number)?.toInt() ?: 2026)
            putInt("syncAdMonth", (data["syncAdMonth"] as? Number)?.toInt() ?: 6)
            putInt("syncAdDay", (data["syncAdDay"] as? Number)?.toInt() ?: 23)

            putInt("syncBsYear", (data["syncBsYear"] as? Number)?.toInt() ?: 2083)
            putInt("syncBsMonth", (data["syncBsMonth"] as? Number)?.toInt() ?: 3)
            putInt("syncBsDay", (data["syncBsDay"] as? Number)?.toInt() ?: 9)

            putInt("daysInMonth", (data["daysInMonth"] as? Number)?.toInt() ?: 31)
            putInt("firstDayWeekday", (data["firstDayWeekday"] as? Number)?.toInt() ?: 3)

            // Save JSON strings
            putString("monthDaysData", data["monthDaysData"] as? String ?: "")
            putString("holidays", data["holidays"] as? String ?: "")

            // Save the dynamic out-of-bounds cross-over arrays generated by Flutter
            for (offset in -2..5) {
                if (offset == 0) continue
                putInt("targetBsDay_$offset", (data["targetBsDay_$offset"] as? Number)?.toInt() ?: 0)
                putInt("targetBsMonth_$offset", (data["targetBsMonth_$offset"] as? Number)?.toInt() ?: 0)
                putInt("targetBsYear_$offset", (data["targetBsYear_$offset"] as? Number)?.toInt() ?: 0)
                putInt("targetDaysInMonth_$offset", (data["targetDaysInMonth_$offset"] as? Number)?.toInt() ?: 0)
                putInt("targetFirstWeekday_$offset", (data["targetFirstWeekday_$offset"] as? Number)?.toInt() ?: 0)
            }
            apply()
        }
    }

    private fun triggerWidgetUpdate() {
        updateForProvider(BhittePatroWidgetProvider::class.java)
        updateForProvider(BhittePatroWidgetProviderMedium::class.java)
    }

    private fun <T> updateForProvider(providerClass: Class<T>) {
        val intent = Intent(context, providerClass).apply {
            action = AppWidgetManager.ACTION_APPWIDGET_UPDATE
        }
        val ids = AppWidgetManager.getInstance(application).getAppWidgetIds(
            ComponentName(application, providerClass)
        )
        intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids)
        context.sendBroadcast(intent)
    }
}
