// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwgHO356eyVogcIxwHT2hz7zbvMXO2UWc',
    appId: '1:236364759427:web:38419ec5a0b44b6d83f6b6',
    messagingSenderId: '236364759427',
    projectId: 'bhittepatro-256bc',
    authDomain: 'bhittepatro-256bc.firebaseapp.com',
    storageBucket: 'bhittepatro-256bc.firebasestorage.app',
    measurementId: 'G-CH71GVCZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeO91A67H7muqqJSajgj1NFOZSdq95mtQ',
    appId: '1:236364759427:android:0a642cf0e68b5bbf83f6b6',
    messagingSenderId: '236364759427',
    projectId: 'bhittepatro-256bc',
    storageBucket: 'bhittepatro-256bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57mRA470tcwMmMnBoR-f6ya9wpGonkus',
    appId: '1:236364759427:ios:2fb8f666b85f824a83f6b6',
    messagingSenderId: '236364759427',
    projectId: 'bhittepatro-256bc',
    storageBucket: 'bhittepatro-256bc.firebasestorage.app',
    iosClientId: '236364759427-3glo6r9gbuchihbbdg07dj8ujllf9dfg.apps.googleusercontent.com',
    iosBundleId: 'com.pranab.bhittePatro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD57mRA470tcwMmMnBoR-f6ya9wpGonkus',
    appId: '1:236364759427:ios:95979095351fb78683f6b6',
    messagingSenderId: '236364759427',
    projectId: 'bhittepatro-256bc',
    storageBucket: 'bhittepatro-256bc.firebasestorage.app',
    iosClientId: '236364759427-aiebfqtpthrl4a2pepl4u2rol0lp3oeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhittePatro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwgHO356eyVogcIxwHT2hz7zbvMXO2UWc',
    appId: '1:236364759427:web:9fcfaebd09dbd63383f6b6',
    messagingSenderId: '236364759427',
    projectId: 'bhittepatro-256bc',
    authDomain: 'bhittepatro-256bc.firebaseapp.com',
    storageBucket: 'bhittepatro-256bc.firebasestorage.app',
    measurementId: 'G-NG2QYL1K9G',
  );
}
